In [107]:
import numpy as np
print(np.__version__)
print(np.show_config())

1.19.2
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/dell/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/dell/anaconda3\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/dell/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/dell/anaconda3\\Library\\include']
lapack_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/dell/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/dell/anaconda3\\Library\\include']
lapack_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/dell/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/dell/anaconda3\\Library\\include']
None


In [108]:
z = np.zeros(10)
print(z)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [109]:
array = np.array([1,2,3,4,5])
print(type(a))
print(a.dtype)

<class 'numpy.ndarray'>
int32


In [110]:
print(a.ndim)
print(a.itemsize)
print(a.nbytes)

1
4
80


In [111]:
n_v = np.zeros(10)
n_v[4] = 1
print(n_v)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [112]:
a = np.arange(10,50,1)
print(a)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [113]:
print(a[::-1])

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


In [114]:
a  = np.arange(0,9)
a.reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [115]:
a = np.array([1,2,0,0,4,0])
np.nonzero(a)

(array([0, 1, 4], dtype=int64),)

In [116]:
a = np.identity(3)
a

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [117]:
a = np.random.rand(3,3,3)
a

array([[[0.94297048, 0.77118875, 0.1276896 ],
        [0.38280523, 0.35241906, 0.3305655 ],
        [0.92798751, 0.60781842, 0.75651711]],

       [[0.87725979, 0.11803354, 0.99249011],
        [0.01080021, 0.09949179, 0.95480265],
        [0.35633032, 0.24421603, 0.1697624 ]],

       [[0.30092924, 0.47935324, 0.27173737],
        [0.71622742, 0.1425258 , 0.01391525],
        [0.22090622, 0.12452476, 0.72416741]]])

In [118]:
array = np.random.rand(10,10)
print(array.max())
print(array.min())

0.9974776857442019
0.009607883016804264


In [119]:
array = np.random.rand(6,5)
print(array.mean())

0.42857861115741736


In [120]:
a = np.ones((5,5))
a[1:4, 1:4] = 0
a

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

In [121]:
a = np.ones((4,4))
a[:1, :] = 0
a[3:, :] = 0
a[:,:1] = 0
a[:,3:] = 0
a

array([[0., 0., 0., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [0., 0., 0., 0.]])

In [122]:
array = np.arange(1,15).reshape(2,7)
print(array[1,5])
print(array[0,:])
print(array[:,2])
print(array[0,1::2])
array[1,5] = 20
array

13
[1 2 3 4 5 6 7]
[ 3 10]
[2 4 6]


array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 20, 14]])

In [123]:
array = np.arange(1,5)
print(array.ndim)
array.reshape((2,2))

1


array([[1, 2],
       [3, 4]])

In [124]:
a = np.array([1,2,3])
np.append(np.repeat(a,3),np.tile(a,3))

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

In [125]:
import sys
a = range(20)
l = len(a)
print(sys.getsizeof(a)*l)

a  = np.arange(20)
print(a.size*a.itemsize)

960
80


In [126]:
import time
import sys
size = 10000000
l1 = range(size)
l2 = range(size)
start = time.time()
result = [(x * y) for x,y in zip(l1, l2)]
print("Time taken by List: ", (time.time() - start), "seconds")

l1 = np.arange(size)
l2 = np.arange(size)
start1 = time.time()
res = l1 * l2
print("Time taken by numpy array: ", (time.time() - start1), "seconds")

Time taken by List:  3.6635446548461914 seconds
Time taken by numpy array:  0.05832409858703613 seconds
